# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

workspace 'EaseChatKitDemo.xcworkspace'

target 'EaseChatKitDemo' do
  pod 'AgoraChat'
  pod 'Masonry'
  pod 'EaseChatKit',  :path => "../"
end


